добавляет валидацию заголовка, цены и комнат
htmlacademy-javascript/1944511-keksobooking-26 pull request #7
Opened 2022-07-09 20:09 UTC by igorr28

2022-07-10 08:57 UTC, pavel-nyukalo requested changes

2022-07-10 08:57 UTC, pavel-nyukalo commented on js/form-validation.js
> +    maxLength: 100
Я бы добавил еще в разметку атрибуты.
Если отвалится JS, то у нас будет хотя бы базовая проверка при помощи HTML.
Так же нудно добавить атрибут `required` всем обязательным полям

2022-07-10 08:57 UTC, pavel-nyukalo commented on js/form-validation.js
> +}
Как я понял из задания, на этом этапе не нужно реализовывать минимальную цену, но не забудь потом добавить

2022-07-11 14:28 UTC, igorr28 commented on js/form-validation.js
> +    maxLength: 100
Добавил атрибуты в html

2022-07-11 14:28 UTC, igorr28 commented on js/form-validation.js
> +}
+

2022-07-11 15:46 UTC, pavel-nyukalo requested changes

2022-07-11 15:46 UTC, pavel-nyukalo commented on index.html
> +          maxlength="100" data-pristine-required-message="Поле обязательно для заполнения">>
Лишняя `>` в конце

2022-07-11 17:47 UTC, igorr28 commented on index.html
> +          maxlength="100" data-pristine-required-message="Поле обязательно для заполнения">>
удалил

2022-07-11 17:58 UTC, pavel-nyukalo approved these changes

2022-07-11 17:58 UTC, merged