Module9 task1
htmlacademy-javascript/1944511-keksobooking-26 pull request #9
Opened 2022-07-16 20:28 UTC by igorr28

2022-07-17 16:16 UTC, pavel-nyukalo requested changes
В целом все отлично 👍🏻

2022-07-17 16:16 UTC, pavel-nyukalo commented on js/form-validation.js
> +    step: 1,
Лучше завести переменные для них, сейчас выглядят как магические числа (а они запрещены критерием). Для старта можно даже не отдельную переменную, а взять из `DATA_VALIDATION`

2022-07-17 16:16 UTC, pavel-nyukalo commented on js/form-validation.js
> +  step: 1,
+1

2022-07-17 16:16 UTC, pavel-nyukalo commented on js/main.js
> +//import { changePageMode } from './form-mode.js';
Если уже не нужно, лучше удалить закомментированный код

2022-07-17 16:16 UTC, pavel-nyukalo commented on js/map.js
> +  }, 14);
14 тоже магическое число

2022-07-17 16:16 UTC, pavel-nyukalo commented on js/map.js
> +  iconAnchor: [20, 40],
1. Под эти тоже давай заведем переменные, чтобы при защите не сказали, что это магические числа.

2. Путь подставляется в разметку, поэтому тут надо указать относительно `index.html`, иначе сервер не может отобразить
![image](https://user-images.githubusercontent.com/52506235/179410918-6e3c1d44-3424-441a-9a0d-ee51d3fabfea.png)

2022-07-17 19:48 UTC, igorr28 commented on js/form-validation.js
> +    step: 1,
исправил

2022-07-17 19:49 UTC, igorr28 commented on js/form-validation.js
> +  step: 1,
исправил

2022-07-17 19:49 UTC, igorr28 commented on js/main.js
> +//import { changePageMode } from './form-mode.js';
исправил

2022-07-17 19:49 UTC, igorr28 commented on js/map.js
> +  }, 14);
исправил

2022-07-17 19:49 UTC, igorr28 commented on js/map.js
> +  iconAnchor: [20, 40],
исправил

2022-07-18 09:21 UTC, pavel-nyukalo approved these changes

2022-07-18 09:21 UTC, merged